### ISSUE TITLE
Create a readme with general guidelines 

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-rfc#1]
This should be RFC-1 --> how to create RFCs and what to do with them once they are created. See, for example, https://github.com/rust-lang/rfcs

**Comment by Panaetius** [comment]
or https://github.com/SwissDataScienceCenter/renku-python/tree/develop/design

**Comment by rokroskar** [comment]
Perfect, we can just bring that over ☺️😅
